exports.delExMrInitDB = {
    date: new Date(),
    data: [{
        hours: "7:00 AM",
        shift: "Shift A",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: "",
    }, {
        hours: "8:00 AM",
        shift: "Shift A",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "9:00 AM",
        shift: "Shift A",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "10:00 AM",
        shift: "Shift A",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "11:00 AM",
        shift: "Shift A",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "12:00 PM",
        shift: "Shift A",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "13:00 PM",
        shift: "Shift A",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "14:00 PM",
        shift: "Shift A; Shift B",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "15:00 PM",
        batch_no: "",
        editHistory: null,
        shift: "Shift B",
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "16:00 PM",
        shift: "Shift B",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "17:00 PM",
        shift: "Shift B",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "18:00 PM",
        shift: "Shift B",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "19:00 PM",
        shift: "Shift B",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "20:00 PM",
        shift: "Shift B",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "21:00 PM",
        shift: "Shift B",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "22:00 PM",
        batch_no: "",
        editHistory: null,
        shift: "Shift B; Shift C",
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "23:00 PM",
        shift: "Shift C",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "24:00 AM",
        shift: "Shift C",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "1:00 AM",
        shift: "Shift C",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "2:00 AM",
        shift: "Shift C",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "3:00 AM",
        shift: "Shift C",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "4:00 AM",
        shift: "Shift C",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "5:00 AM",
        shift: "Shift C",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }, {
        hours: "6:00 AM",
        shift: "Shift C",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    },{
        hours: "7:00 AM",
        shift: "Shift C",
        batch_no: "",
        editHistory: null,
        density: "",
        editedDate: "",
        variation: "",
        fmr: "",
        pumpingBypass: "",
        bypass: "",
        flow_rate_delivery: "",
        flow_rate_pumping: "",
        tank_no: "",
        tank_dip: "",
        flow_Difference: "",
        oficer: ""
    }],
    remarks: {
        "Shift A": "",
        "Shift B": "",
        "Shift C": ""
    }
}