exports.equiRunningHrsMDPLInitDB = {
    date : new Date(),
    data :  [{
      equipment:"BP 1",
      previous:"",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      cummulative:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    equipment:"BP 2",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"MP 1",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"MP 2",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"MP 3",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"INHIBITOR PUMP",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  },  {
    equipment:"SUMP PUMP",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }],
  remarks:""
};