exports.equiRunningHrsBijInitDB = {
    date : new Date(),
    data :  [{
      equipment:"BP 1",
      previousHrs:"",
      previousMin:"",
      shiftAHrs:"",
      shiftAMin:"",
      shiftBHrs:"",
      shiftBMin:"",
      shiftCHrs:"",
      shiftCMin:"",
      cummulativeHrs:"",
      cummulativeMin:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    equipment:"BP 2",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"MP 1",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"MP 2",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"MP 3",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"DG SET",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"FFE",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"FFM",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"SUMP PUMP",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"S/R PUMP",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"OWS PUMP",
    previousHrs:"",
    previousMin:"",
    shiftAHrs:"",
    shiftAMin:"",
    shiftBHrs:"",
    shiftBMin:"",
    shiftCHrs:"",
    shiftCMin:"",
    cummulativeHrs:"",
    cummulativeMin:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }],
  remarks:""
};