exports.equiRunningHrsMTPLMBPLInitDB = {
    date : new Date(),
    data :  [{
      equipment:"BP 3",
      previous:"",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      cummulative:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    equipment:"BP 4",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"MP 4",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"MP 5",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    equipment:"INHIBITOR PUMP",
    previous:"",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    cummulative:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }],
  remarks:""
};