exports.lineFillTableMathuraInitDB = {
    date : new Date(),
    data :  {
      ShiftA :[{
          lineFillName : "Mathura - Bijwasan(MDPL)",
          lineFillVolume : "17738",
          lineFill : []
      },{
          lineFillName : "Mathura - Tundla(MTPL)",
          lineFillVolume : "6995",
          lineFill : []
      },{
          lineFillName : "Mathura - Bharatpur(MBPL)",
          lineFillVolume : "3125",
          lineFill : []
      }],
  ShiftB :[{
    lineFillName : "Mathura - Bijwasan(MDPL)",
    lineFillVolume : "17738",
    lineFill : []
},{
    lineFillName : "Mathura - Tundla(MTPL)",
    lineFillVolume : "6995",
    lineFill : []
},{
    lineFillName : "Mathura - Bharatpur(MBPL)",
    lineFillVolume : "3125",
    lineFill : []
}],
  ShiftC :[{
    lineFillName : "Mathura - Bijwasan(MDPL)",
    lineFillVolume : "17738",
    lineFill : []
},{
    lineFillName : "Mathura - Tundla(MTPL)",
    lineFillVolume : "6995",
    lineFill : []
},{
    lineFillName : "Mathura - Bharatpur(MBPL)",
    lineFillVolume : "3125",
    lineFill : []
}],
  },
  remarks:{
          "Shift A": "",
          "Shift B": "",
          "Shift C": ""
  }
  }