exports.monitoringMtMbMdplInitDB = {
    date : new Date(),
    data: [{
      hours: "7:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "0"
  }, {
      hours: "8:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "1"
  }, {
      hours: "9:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "2"
  }, {
      hours: "10:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "3"
  }, {
      hours: "11:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "4"
  }, {
      hours: "12:00 PM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "5"
  }, {
      hours: "13:00 PM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "6"
  }, {
      hours: "14:00 PM",
      shift: "Shift A; Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "7"
  }, {
      hours: "15:00 PM",
      batch_no: "",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "8"
  }, {
      hours: "16:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "9"
  }, {
      hours: "17:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "10"
  }, {
      hours: "18:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "11"
  }, {
      hours: "19:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "12"
  }, {
      hours: "20:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "13"
  }, {
      hours: "21:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "14"
  }, {
      hours: "22:00 PM",
      batch_no: "",
      shift: "Shift B, Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "15"
  }, {
      hours: "23:00 PM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "16"
  }, {
      hours: "24:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "17"
  }, {
      hours: "1:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "18"
  }, {
      hours: "2:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "19"
  }, {
      hours: "3:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "20"
  }, {
      hours: "4:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "21"
  }, {
      hours: "5:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "22"
  }, {
      hours: "6:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:"", position : "23"
  }, {
    hours: "7:00 AM",
    shift: "Shift C",
    editHistory: null,
    editedDate: "",
    mpr: "",
    tpr: "",
    bpr: "",
    suctionPressure: "",
    pumpNo: "",
    linePressure: "",
    oficer: "", remarks:"", position : "24"
}],
  remarks: {
      "Shift A": "",
      "Shift B": "",
      "Shift C": ""
  }
}