exports.monitoringMtMbMdplInitDB = {
    date : new Date(),
    data: [{
      hours: "7:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "8:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "9:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "10:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "11:00 AM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "12:00 PM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "13:00 PM",
      shift: "Shift A",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "14:00 PM",
      shift: "Shift A; Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "15:00 PM",
      batch_no: "",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "16:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "17:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "18:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "19:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "20:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "21:00 PM",
      shift: "Shift B",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "22:00 PM",
      batch_no: "",
      shift: "Shift B, Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "23:00 PM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "24:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "1:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "2:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "3:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "4:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "5:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
      hours: "6:00 AM",
      shift: "Shift C",
      editHistory: null,
      editedDate: "",
      mpr: "",
      tpr: "",
      bpr: "",
      suctionPressure: "",
      pumpNo: "",
      linePressure: "",
      oficer: "", remarks:""
  }, {
    hours: "7:00 AM",
    shift: "Shift C",
    editHistory: null,
    editedDate: "",
    mpr: "",
    tpr: "",
    bpr: "",
    suctionPressure: "",
    pumpNo: "",
    linePressure: "",
    oficer: "", remarks:""
}],
  remarks: {
      "Shift A": "",
      "Shift B": "",
      "Shift C": ""
  }
}