exports.proInStationLinefillInitDB = {
    date : new Date(),
    data :  [{
      lineLocation:"STN. BP",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    lineLocation:"STN. PMP. LINE",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    lineLocation:"STN. DEL. (MD)",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    remarks:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    lineLocation:"STN. DEL. (PD)",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    lineLocation:"BP 1",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    remarks:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    lineLocation:"BP 2",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    lineLocation:"MP 1",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    remarks:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    lineLocation:"MP 2",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    remarks:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    lineLocation:"MP 3",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    lineLocation:"SEP. FLTR. (MD)",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    lineLocation:"SEP. FLTR. (PD)",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  },{
    lineLocation:"SUMP TK. DIP",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    remarks:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    lineLocation:"S.R.TK.DIP",
    shiftA:"",
    shiftB:"",
    shiftC:"",
    remarks:"",
    editHistory: null,
    editedDate: "",
    oficer: "",
  }, {
    lineLocation:"METER PROVER",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    lineLocation:"TANK LINED UP",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }, {
    lineLocation:"BP TO MOV-708",
      shiftA:"",
      shiftB:"",
      shiftC:"",
      remarks:"",
      editHistory: null,
      editedDate: "",
      oficer: "",
  }],
  remarks:""
};